name: CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    env:
      GitHubMail: "rokibhasansagar2014@outlook.com"
      GitHubName: "rokibhasansagar"

    steps:
      - uses: actions/checkout@v2

      - uses: rokibhasansagar/slimhub_actions@main

      - name: Install expect
        run: |
          sudo apt-get install -qy expect

      - name: cloning repo
        run: |
          git config --global user.email $GitHubMail
          git config --global user.name $GitHubName
          expect -c "
          spawn git clone https://github.com/$GitHubName/${{ secrets.MIRROR_TOOL }} -b production source
          expect \"Username\"        
          send \"${GitHubName}\r\"
          expect \"Password\"        
          send \"${{ secrets.GH_TOKEN }}\r\"
          set timeout -1
          catch wait result
          interact"

      - name: compilation
        run: |
          cd source
          docker container prune --force || true
          docker build . -t mirror-bot

      - name: running Docker
        timeout-minutes: 320
        run: |
          docker run mirror-bot

      - name: Loop workflow
        continue-on-error: true
        run: |
          git clone https://${{ secrets.GH_TOKEN }}@github.com/$GitHubName/TGMirrorLooper loop
          cd loop
          echo $(( RANDOM - ( RANDOM % RANDOM ) )) > looper.txt
          git add looper.txt
          git commit -as -m "Looping at $(date -u +%s)"
          expect -c "
          spawn git push -f
          expect \"Username\"        
          send \"${GitHubName}\r\"
          expect \"Password\"        
          send \"${{ secrets.GH_TOKEN }}\r\"
          expect \"main -> main\"
          set timeout -10
          interact"
