name: CI

on:
  push:
    branches: [ main ]
    paths-ignore: 'README.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GitHubMail: ${{ secrets.GitHubMail }}
      GitHubName: ${{ secrets.GitHubName }}

    steps:
      - name: Set Git Configs & Secrets
        run: |
          git config --global user.email ${GitHubMail}
          git config --global user.name ${GitHubName}
          git config --global credential.helper store
          echo "https://${GitHubName}:${{ secrets.GH_TOKEN }}@github.com" > ~/.git-credentials
      # Cleanup The Actions Workspace Using Custom Composite Run Actions
      - uses: rokibhasansagar/slimhub_actions@main
      - name: Clone The Mirror Repository
        run: |
          mkdir -p /home/runner/magnetoBot
          cd /home/runner
          git clone https://${{ secrets.GH_TOKEN }}@github.com/${{ secrets.MIRROR_REPOSLUG }} \
            --branch master --depth 1 magnetoBot
      - name: Compile The Mirroring Docker Container
        run: |
          cd /home/runner/magnetoBot || exit 1
          curl -sL https://gist.github.com/rokibhasansagar/${{ secrets.MagnetoConfigSlug }} -o config.env
          curl -sL https://gist.github.com/rokibhasansagar/${{ secrets.MagnetoCredsSlug }} -o credentials.json
          curl -sL https://gist.github.com/rokibhasansagar/${{ secrets.MagnetoPickleSlug }} | base64 --decode >> token.pickle
          docker container prune --force || true
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin &>/dev/null
          docker build . --rm --force-rm --compress --no-cache=true --pull --file Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/mirror-bot:latest
          docker image ls
          docker push ${{ secrets.DOCKER_USERNAME }}/mirror-bot:latest
      - name: Run The Mirroring Docker Container
        continue-on-error: true
        timeout-minutes: 320
        run: |
          cd /home/runner/magnetoBot || exit 1
          docker run --privileged --rm -i ${{ secrets.DOCKER_USERNAME }}/mirror-bot:latest
      - name: Trigger The Looper
        run: |
          curl -X POST --header "Authorization: token ${{ secrets.GH_TOKEN }}" https://api.github.com/repos/${GITHUB_REPOSITORY}/actions/workflows/main.yml/dispatches -d '{"ref":"main"}'
